title: IBISC documentation
description: A starter template for the documentation of the laboratory
logo: /assets/images/logo.png
url: https://ibisc-documentation.github.io
remote_theme: pmarsceill/just-the-docs
